# fly.toml app configuration file generated for school-management on 2024-04-05T23:34:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'school-management'
primary_region = 'ams'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
